### ISSUE TITLE
Base project (with added nodemon) is crashing.

### ISSUE THREAD

**Issue by karlkras** [StephenGrider/auth-graphql-starter#4]
npm version 5.3.0 (also tried with 3.8.0)
using nodemon: "*" added to package.json since not in project.

`
~/work/mywork/auth-graphql-starter (master)*> npm run dev

> users@1.0.0 dev /Users/kkras2/work/NikeDev/mywork/auth-graphql-starter
> nodemon index.js --ignore client

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
/Users/kkras2/work/NikeDev/mywork/auth-graphql-starter/node_modules/graphql/jsutils/invariant.js:19
    throw new Error(message);
    ^

Error: RootQueryType fields must be an object with field names as keys or a function which returns such an object.
    at invariant (/Users/kkras2/work/NikeDev/mywork/auth-graphql-starter/node_modules/graphql/jsutils/invariant.js:19:11)
    at defineFieldMap (/Users/kkras2/work/NikeDev/mywork/auth-graphql-starter/node_modules/graphql/type/definition.js:312:27)
    at GraphQLObjectType.getFields (/Users/kkras2/work/NikeDev/mywork/auth-graphql-starter/node_modules/graphql/type/definition.js:276:44)
    at /Users/kkras2/work/NikeDev/mywork/auth-graphql-starter/node_modules/graphql/type/schema.js:207:27
    at typeMapReducer (/Users/kkras2/work/NikeDev/mywork/auth-graphql-starter/node_modules/graphql/type/schema.js:219:7)
    at Array.reduce (native)
    at new GraphQLSchema (/Users/kkras2/work/NikeDev/mywork/auth-graphql-starter/node_modules/graphql/type/schema.js:95:34)
    at Object.<anonymous> (/Users/kkras2/work/NikeDev/mywork/auth-graphql-starter/server/schema/schema.js:6:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kkras2/work/NikeDev/mywork/auth-graphql-starter/server/server.js:9:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
[nodemon] app crashed - waiting for file changes before starting...
~/work/auth-graphql-starter (master)*> npm -v
`
As a result I'm blocked in this course.

**Comment by alexboots** [comment]
I presume this gets fixed in tutorials (haven't went through them yet) but to fix this you need to add a `fields` method when declaring a `new GraphQLObjectType` 

So in the file `./server/schema/types/root_query_type.js` you need to import some type, say `GraphQLString`, and add the fields key

```
const { GraphQLObjectType, GraphQLString } = graphql;

const RootQueryType = new GraphQLObjectType({
  name: 'RootQueryType',
  fields: () => ({
    someTempThing: { type: GraphQLString }
  })
});
```
